[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "flask-restx>=1.3.0",
    "pydantic>=2.11.0",
    "replit>=4.1.1",
]
